server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: accounts
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/accounts/**

        - id: rates
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/rates/**
