server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            corsConfigurations:
              '[/**]':
                allowedOrigins: "http://localhost:9090"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
          routes:
            - id: accounts
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/accounts/**
              filters:
                - RewritePath=/api/v1/accounts/(?<segment>.*), /api/v1/${segment}

            - id: exchange
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/exchange/**
              filters:
                - RewritePath=/api/v1/exchange/(?<segment>.*), /api/v1/${segment}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG