spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: ${KEYCLOAK_CLIENT_ID}
#            client-secret: ${KEYCLOAK_CLIENT_SECRET}
#            authorization-grant-type: client_credentials
#        provider:
#          keycloak:
#            token-uri: http://keycloak:8080/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
  application:
    name: accounts
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

#payment:
#  api:
#    url: ${PAYMENT_API_URL}
